#ifndef INCLUDE_QUADRUPED_CONTROL_LIBRARY_CONVEXMPC_HPP
#define INCLUDE_QUADRUPED_CONTROL_LIBRARY_CONVEXMPC_HPP

#include <qpOASES.hpp>

class  ConvexMPC{
public:

private:
};

#endif /* INCLUDE_QUADRUPED_CONTROL_LIBRARY_CONVEXMPC_HPP */
