#ifndef INCLUDE_QUADRUPED_CONTROL_LIBRARY_FIXEDFOOTPLANNER_HPP
#define INCLUDE_QUADRUPED_CONTROL_LIBRARY_FIXEDFOOTPLANNER_HPP



class FixedFootPlanner
{
};

#endif /* INCLUDE_QUADRUPED_CONTROL_LIBRARY_FIXEDFOOTPLANNER_HPP */
